services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 100m
  homecam:
    image: tuna1025/homecam:latest
    container_name: homecam
    network_mode: "host"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
volumes:
  redis-data: